### ISSUE TITLE
JSX IntrinsicElements

### ISSUE THREAD

**Issue by acroyear** [michijs/michijs#170]
Not a bug so much as a suggestion - yes, probably the preferred way for JSX is to use the name itself <MyCounter> which already gets all the props.

But if you're a coder who wants to be consistent about using the web-component hyphenated syntax, the typescript will block that because my-counter (for example) is not defined.

Here's how you can fix that and keep type safety - just add this to the bottom of each component file (with the types changed, of course).

```
type MyCounterConstructorParamters = ConstructorParameters<typeof MyCounter>;
export type MyCounterProps = MyCounterConstructorParamters[0];
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "my-counter": MyCounterProps
    }
  }
}
```

**Comment by lsegurado** [comment]
I thought about it when I started the project. The problem with that approach is that it can give the false illusion that the component is registered just by installing the package/building the component; which is not correct. With that approach there are two options:

1. Import the component file into your parent component
2. Import all the components you need in a main app file

The first scenario is buggy, since you could be importing components that you no longer use in the parent component or you could forget to import it, which would not work. But it would still allow lazy loading.
The second scenario involves creating a bundle with all the files necessary for the application to work but the modern web tends to abandon that approach (since it is not efficient - it does not use lazy loading) so I do not recommend doing it.
In any case if you still want to do it there is a type that helps to get props from any component `GetElementProps`
